services:
  mongodb:
    image: mongo:7.0.6
    container_name: crocodile_mongodb
    ports:
      - "${MONGO_SERVER_PORT}:27017"
    volumes:
      - ./mongo_data:/data/db  # Local directory for MongoDB data
    
  jupyter:
    image: roby944/jupyter-minimal-extended:latest
    container_name: crocodile_jupyter
    ports:
      - "${JUPYTER_SERVER_PORT}:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./crocodile:/home/jovyan/work/crocodile
      - ./tables:/home/jovyan/work/tables
      - ./training/:/home/jovyan/work/training
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    environment:
      - JUPYTER_ENABLE_LAB=yes
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - mongodb